export namespace ts3_webquery {
	
	export class Body {
	    apikey?: string;
	    cldbid?: string;
	    created_at?: string;
	    expires_at?: string;
	    id?: string;
	    scope?: string;
	    sid?: string;
	    time_left?: string;
	    count?: string;
	    banid?: string;
	    created?: string;
	    duration?: string;
	    enforcements?: string;
	    invokercldbid?: string;
	    invokername?: string;
	    invokeruid?: string;
	    ip?: string;
	    lastnickname?: string;
	    mytsid?: string;
	    name?: string;
	    reason?: string;
	    uid?: string;
	    cid?: string;
	    permid?: string;
	    permvalue?: string;
	    permnegated?: string;
	    channel_name?: string;
	    cgid?: string;
	    type?: string;
	    iconid?: string;
	    savedb?: string;
	    permskip?: string;
	    channel_banner_gfx_url?: string;
	    channel_banner_mode?: string;
	    channel_codec?: string;
	    channel_codec_is_unencrypted?: string;
	    channel_codec_latency_factor?: string;
	    channel_codec_quality?: string;
	    channel_delete_delay?: string;
	    channel_description?: string;
	    channel_filepath?: string;
	    channel_flag_default?: string;
	    channel_flag_maxclients_unlimited?: string;
	    channel_flag_maxfamilyclients_inherited?: string;
	    channel_flag_maxfamilyclients_unlimited?: string;
	    channel_flag_password?: string;
	    channel_flag_permanent?: string;
	    channel_flag_semi_permanent?: string;
	    channel_forced_silence?: string;
	    channel_icon_id?: string;
	    channel_maxclients?: string;
	    channel_maxfamilyclients?: string;
	    channel_name_phonetic?: string;
	    channel_needed_talk_power?: string;
	    channel_order?: string;
	    channel_password?: string;
	    channel_security_salt?: string;
	    channel_topic?: string;
	    channel_unique_identifier?: string;
	    pid?: string;
	    seconds_empty?: string;
	    channel_needed_subscribe_power?: string;
	    total_clients?: string;
	    total_clients_family?: string;
	    client_base64HashClientUID?: string;
	    client_created?: string;
	    client_database_id?: string;
	    client_description?: string;
	    client_flag_avatar?: string;
	    client_lastconnected?: string;
	    client_lastip?: string;
	    client_month_bytes_downloaded?: string;
	    client_month_bytes_uploaded?: string;
	    client_nickname?: string;
	    client_total_bytes_downloaded?: string;
	    client_total_bytes_uploaded?: string;
	    client_totalconnections?: string;
	    client_unique_identifier?: string;
	    client_login_name?: string;
	    clid?: string;
	    cluid?: string;
	    client_away?: string;
	    client_away_message?: string;
	    client_badges?: string;
	    client_channel_group_id?: string;
	    client_channel_group_inherited_channel_id?: string;
	    client_country?: string;
	    client_default_channel?: string;
	    client_default_token?: string;
	    client_icon_id?: string;
	    client_idle_time?: string;
	    client_input_hardware?: string;
	    client_input_muted?: string;
	    client_integrations?: string;
	    client_is_channel_commander?: string;
	    client_is_priority_speaker?: string;
	    client_is_recording?: string;
	    client_is_talker?: string;
	    client_meta_data?: string;
	    client_myteamspeak_avatar?: string;
	    client_myteamspeak_id?: string;
	    client_needed_serverquery_view_power?: string;
	    client_nickname_phonetic?: string;
	    client_output_hardware?: string;
	    client_output_muted?: string;
	    client_outputonly_muted?: string;
	    client_platform?: string;
	    client_security_hash?: string;
	    client_servergroups?: string;
	    client_signed_badges?: string;
	    client_talk_power?: string;
	    client_talk_request?: string;
	    client_talk_request_msg?: string;
	    client_type?: string;
	    client_unread_messages?: string;
	    client_version?: string;
	    client_version_sign?: string;
	    connection_bandwidth_received_last_minute_total?: string;
	    connection_bandwidth_received_last_second_total?: string;
	    connection_bandwidth_sent_last_minute_total?: string;
	    connection_bandwidth_sent_last_second_total?: string;
	    connection_bytes_received_total?: string;
	    connection_bytes_sent_total?: string;
	    connection_client_ip?: string;
	    connection_connected_time?: string;
	    connection_filetransfer_bandwidth_received?: string;
	    connection_filetransfer_bandwidth_sent?: string;
	    connection_packets_received_total?: string;
	    connection_packets_sent_total?: string;
	    client_login_password?: string;
	    fcldbid?: string;
	    fname?: string;
	    message?: string;
	    tcldbid?: string;
	    timestamp?: number;
	    tname?: string;
	    ident?: string;
	    value?: string;
	    size?: string;
	    connection_filetransfer_bytes_received_total?: string;
	    connection_filetransfer_bytes_sent_total?: string;
	    host_timestamp_utc?: string;
	    instance_uptime?: string;
	    virtualservers_running_total?: string;
	    virtualservers_total_channels_online?: string;
	    virtualservers_total_clients_online?: string;
	    virtualservers_total_maxclients?: string;
	    serverinstance_database_version?: string;
	    serverinstance_filetransfer_port?: string;
	    serverinstance_guest_serverquery_group?: string;
	    serverinstance_max_download_total_bandwidth?: string;
	    serverinstance_max_upload_total_bandwidth?: string;
	    serverinstance_pending_connections_per_ip?: string;
	    serverinstance_permissions_version?: string;
	    serverinstance_serverquery_ban_time?: string;
	    serverinstance_serverquery_flood_commands?: string;
	    serverinstance_serverquery_flood_time?: string;
	    serverinstance_serverquery_max_connections_per_ip?: string;
	    serverinstance_template_channeladmin_group?: string;
	    serverinstance_template_channeldefault_group?: string;
	    serverinstance_template_serveradmin_group?: string;
	    serverinstance_template_serverdefault_group?: string;
	    file_size?: string;
	    l?: string;
	    last_pos?: string;
	    msgid?: string;
	    subject?: string;
	    permsid?: string;
	    permname?: string;
	    permdesc?: string;
	    token?: string;
	    token_created?: string;
	    token_customset?: string;
	    token_description?: string;
	    token_id1?: string;
	    token_id2?: string;
	    token_type?: string;
	    virtualserver_port?: string;
	    sgid?: string;
	    n_member_addp?: string;
	    n_member_removep?: string;
	    n_modifyp?: string;
	    namemode?: string;
	    sortid?: string;
	    server_id?: string;
	    connection_bytes_received_control?: string;
	    connection_bytes_received_speech?: string;
	    connection_bytes_sent_control?: string;
	    connection_bytes_received_keepalive?: string;
	    connection_bytes_sent_keepalive?: string;
	    connection_bytes_sent_speech?: string;
	    connection_packets_received_control?: string;
	    connection_packets_received_keepalive?: string;
	    connection_packets_received_speech?: string;
	    connection_packets_sent_control?: string;
	    connection_packets_sent_keepalive?: string;
	    connection_packets_sent_speech?: string;
	    virtualserver_antiflood_points_needed_command_block?: string;
	    virtualserver_antiflood_points_needed_ip_block?: string;
	    virtualserver_antiflood_points_needed_plugin_block?: string;
	    virtualserver_antiflood_points_tick_reduce?: string;
	    virtualserver_ask_for_privilegekey?: string;
	    virtualserver_autostart?: string;
	    virtualserver_capability_extensions?: string;
	    virtualserver_channel_temp_delete_delay_default?: string;
	    virtualserver_channelsonline?: string;
	    virtualserver_client_connections?: string;
	    virtualserver_clientsonline?: string;
	    virtualserver_codec_encryption_mode?: string;
	    virtualserver_complain_autoban_count?: string;
	    virtualserver_complain_autoban_time?: string;
	    virtualserver_complain_remove_time?: string;
	    virtualserver_created?: string;
	    virtualserver_default_channel_admin_group?: string;
	    virtualserver_default_channel_group?: string;
	    virtualserver_default_server_group?: string;
	    virtualserver_download_quota?: string;
	    virtualserver_file_storage_class?: string;
	    virtualserver_filebase?: string;
	    virtualserver_flag_password?: string;
	    virtualserver_hostbanner_gfx_interval?: string;
	    virtualserver_hostbanner_gfx_url?: string;
	    virtualserver_hostbanner_mode?: string;
	    virtualserver_hostbanner_url?: string;
	    virtualserver_hostbutton_gfx_url?: string;
	    virtualserver_hostbutton_tooltip?: string;
	    virtualserver_hostbutton_url?: string;
	    virtualserver_hostmessage?: string;
	    virtualserver_hostmessage_mode?: string;
	    virtualserver_icon_id?: string;
	    virtualserver_id?: string;
	    virtualserver_ip?: string;
	    virtualserver_log_channel?: string;
	    virtualserver_log_client?: string;
	    virtualserver_log_filetransfer?: string;
	    virtualserver_log_permissions?: string;
	    virtualserver_log_query?: string;
	    virtualserver_log_server?: string;
	    virtualserver_machine_id?: string;
	    virtualserver_max_download_total_bandwidth?: string;
	    virtualserver_max_upload_total_bandwidth?: string;
	    virtualserver_maxclients?: string;
	    virtualserver_min_android_version?: string;
	    virtualserver_min_client_version?: string;
	    virtualserver_min_clients_in_channel_before_forced_silence?: string;
	    virtualserver_min_ios_version?: string;
	    virtualserver_month_bytes_downloaded?: string;
	    virtualserver_month_bytes_uploaded?: string;
	    virtualserver_name?: string;
	    virtualserver_name_phonetic?: string;
	    virtualserver_needed_identity_security_level?: string;
	    virtualserver_nickname?: string;
	    virtualserver_password?: string;
	    virtualserver_platform?: string;
	    virtualserver_priority_speaker_dimm_modificator?: string;
	    virtualserver_query_client_connections?: string;
	    virtualserver_queryclientsonline?: string;
	    virtualserver_reserved_slots?: string;
	    virtualserver_status?: string;
	    virtualserver_total_bytes_downloaded?: string;
	    virtualserver_total_bytes_uploaded?: string;
	    virtualserver_total_packetloss_control?: string;
	    virtualserver_total_packetloss_keepalive?: string;
	    virtualserver_total_packetloss_speech?: string;
	    virtualserver_total_packetloss_total?: string;
	    virtualserver_total_ping?: string;
	    virtualserver_unique_identifier?: string;
	    virtualserver_upload_quota?: string;
	    virtualserver_uptime?: string;
	    virtualserver_version?: string;
	    virtualserver_weblist_enabled?: string;
	    virtualserver_welcomemessage?: string;
	    connection_packetloss_total?: string;
	    connection_ping?: string;
	    data?: string;
	    version?: string;
	    nickname?: string;
	    desc?: string;
	    pw_clear?: string;
	    start?: string;
	    end?: string;
	    tcid?: string;
	    build?: string;
	    platform?: string;
	    client_channel_id?: string;
	    client_id?: string;
	    client_origin_server_id?: string;
	
	    static createFrom(source: any = {}) {
	        return new Body(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.apikey = source["apikey"];
	        this.cldbid = source["cldbid"];
	        this.created_at = source["created_at"];
	        this.expires_at = source["expires_at"];
	        this.id = source["id"];
	        this.scope = source["scope"];
	        this.sid = source["sid"];
	        this.time_left = source["time_left"];
	        this.count = source["count"];
	        this.banid = source["banid"];
	        this.created = source["created"];
	        this.duration = source["duration"];
	        this.enforcements = source["enforcements"];
	        this.invokercldbid = source["invokercldbid"];
	        this.invokername = source["invokername"];
	        this.invokeruid = source["invokeruid"];
	        this.ip = source["ip"];
	        this.lastnickname = source["lastnickname"];
	        this.mytsid = source["mytsid"];
	        this.name = source["name"];
	        this.reason = source["reason"];
	        this.uid = source["uid"];
	        this.cid = source["cid"];
	        this.permid = source["permid"];
	        this.permvalue = source["permvalue"];
	        this.permnegated = source["permnegated"];
	        this.channel_name = source["channel_name"];
	        this.cgid = source["cgid"];
	        this.type = source["type"];
	        this.iconid = source["iconid"];
	        this.savedb = source["savedb"];
	        this.permskip = source["permskip"];
	        this.channel_banner_gfx_url = source["channel_banner_gfx_url"];
	        this.channel_banner_mode = source["channel_banner_mode"];
	        this.channel_codec = source["channel_codec"];
	        this.channel_codec_is_unencrypted = source["channel_codec_is_unencrypted"];
	        this.channel_codec_latency_factor = source["channel_codec_latency_factor"];
	        this.channel_codec_quality = source["channel_codec_quality"];
	        this.channel_delete_delay = source["channel_delete_delay"];
	        this.channel_description = source["channel_description"];
	        this.channel_filepath = source["channel_filepath"];
	        this.channel_flag_default = source["channel_flag_default"];
	        this.channel_flag_maxclients_unlimited = source["channel_flag_maxclients_unlimited"];
	        this.channel_flag_maxfamilyclients_inherited = source["channel_flag_maxfamilyclients_inherited"];
	        this.channel_flag_maxfamilyclients_unlimited = source["channel_flag_maxfamilyclients_unlimited"];
	        this.channel_flag_password = source["channel_flag_password"];
	        this.channel_flag_permanent = source["channel_flag_permanent"];
	        this.channel_flag_semi_permanent = source["channel_flag_semi_permanent"];
	        this.channel_forced_silence = source["channel_forced_silence"];
	        this.channel_icon_id = source["channel_icon_id"];
	        this.channel_maxclients = source["channel_maxclients"];
	        this.channel_maxfamilyclients = source["channel_maxfamilyclients"];
	        this.channel_name_phonetic = source["channel_name_phonetic"];
	        this.channel_needed_talk_power = source["channel_needed_talk_power"];
	        this.channel_order = source["channel_order"];
	        this.channel_password = source["channel_password"];
	        this.channel_security_salt = source["channel_security_salt"];
	        this.channel_topic = source["channel_topic"];
	        this.channel_unique_identifier = source["channel_unique_identifier"];
	        this.pid = source["pid"];
	        this.seconds_empty = source["seconds_empty"];
	        this.channel_needed_subscribe_power = source["channel_needed_subscribe_power"];
	        this.total_clients = source["total_clients"];
	        this.total_clients_family = source["total_clients_family"];
	        this.client_base64HashClientUID = source["client_base64HashClientUID"];
	        this.client_created = source["client_created"];
	        this.client_database_id = source["client_database_id"];
	        this.client_description = source["client_description"];
	        this.client_flag_avatar = source["client_flag_avatar"];
	        this.client_lastconnected = source["client_lastconnected"];
	        this.client_lastip = source["client_lastip"];
	        this.client_month_bytes_downloaded = source["client_month_bytes_downloaded"];
	        this.client_month_bytes_uploaded = source["client_month_bytes_uploaded"];
	        this.client_nickname = source["client_nickname"];
	        this.client_total_bytes_downloaded = source["client_total_bytes_downloaded"];
	        this.client_total_bytes_uploaded = source["client_total_bytes_uploaded"];
	        this.client_totalconnections = source["client_totalconnections"];
	        this.client_unique_identifier = source["client_unique_identifier"];
	        this.client_login_name = source["client_login_name"];
	        this.clid = source["clid"];
	        this.cluid = source["cluid"];
	        this.client_away = source["client_away"];
	        this.client_away_message = source["client_away_message"];
	        this.client_badges = source["client_badges"];
	        this.client_channel_group_id = source["client_channel_group_id"];
	        this.client_channel_group_inherited_channel_id = source["client_channel_group_inherited_channel_id"];
	        this.client_country = source["client_country"];
	        this.client_default_channel = source["client_default_channel"];
	        this.client_default_token = source["client_default_token"];
	        this.client_icon_id = source["client_icon_id"];
	        this.client_idle_time = source["client_idle_time"];
	        this.client_input_hardware = source["client_input_hardware"];
	        this.client_input_muted = source["client_input_muted"];
	        this.client_integrations = source["client_integrations"];
	        this.client_is_channel_commander = source["client_is_channel_commander"];
	        this.client_is_priority_speaker = source["client_is_priority_speaker"];
	        this.client_is_recording = source["client_is_recording"];
	        this.client_is_talker = source["client_is_talker"];
	        this.client_meta_data = source["client_meta_data"];
	        this.client_myteamspeak_avatar = source["client_myteamspeak_avatar"];
	        this.client_myteamspeak_id = source["client_myteamspeak_id"];
	        this.client_needed_serverquery_view_power = source["client_needed_serverquery_view_power"];
	        this.client_nickname_phonetic = source["client_nickname_phonetic"];
	        this.client_output_hardware = source["client_output_hardware"];
	        this.client_output_muted = source["client_output_muted"];
	        this.client_outputonly_muted = source["client_outputonly_muted"];
	        this.client_platform = source["client_platform"];
	        this.client_security_hash = source["client_security_hash"];
	        this.client_servergroups = source["client_servergroups"];
	        this.client_signed_badges = source["client_signed_badges"];
	        this.client_talk_power = source["client_talk_power"];
	        this.client_talk_request = source["client_talk_request"];
	        this.client_talk_request_msg = source["client_talk_request_msg"];
	        this.client_type = source["client_type"];
	        this.client_unread_messages = source["client_unread_messages"];
	        this.client_version = source["client_version"];
	        this.client_version_sign = source["client_version_sign"];
	        this.connection_bandwidth_received_last_minute_total = source["connection_bandwidth_received_last_minute_total"];
	        this.connection_bandwidth_received_last_second_total = source["connection_bandwidth_received_last_second_total"];
	        this.connection_bandwidth_sent_last_minute_total = source["connection_bandwidth_sent_last_minute_total"];
	        this.connection_bandwidth_sent_last_second_total = source["connection_bandwidth_sent_last_second_total"];
	        this.connection_bytes_received_total = source["connection_bytes_received_total"];
	        this.connection_bytes_sent_total = source["connection_bytes_sent_total"];
	        this.connection_client_ip = source["connection_client_ip"];
	        this.connection_connected_time = source["connection_connected_time"];
	        this.connection_filetransfer_bandwidth_received = source["connection_filetransfer_bandwidth_received"];
	        this.connection_filetransfer_bandwidth_sent = source["connection_filetransfer_bandwidth_sent"];
	        this.connection_packets_received_total = source["connection_packets_received_total"];
	        this.connection_packets_sent_total = source["connection_packets_sent_total"];
	        this.client_login_password = source["client_login_password"];
	        this.fcldbid = source["fcldbid"];
	        this.fname = source["fname"];
	        this.message = source["message"];
	        this.tcldbid = source["tcldbid"];
	        this.timestamp = source["timestamp"];
	        this.tname = source["tname"];
	        this.ident = source["ident"];
	        this.value = source["value"];
	        this.size = source["size"];
	        this.connection_filetransfer_bytes_received_total = source["connection_filetransfer_bytes_received_total"];
	        this.connection_filetransfer_bytes_sent_total = source["connection_filetransfer_bytes_sent_total"];
	        this.host_timestamp_utc = source["host_timestamp_utc"];
	        this.instance_uptime = source["instance_uptime"];
	        this.virtualservers_running_total = source["virtualservers_running_total"];
	        this.virtualservers_total_channels_online = source["virtualservers_total_channels_online"];
	        this.virtualservers_total_clients_online = source["virtualservers_total_clients_online"];
	        this.virtualservers_total_maxclients = source["virtualservers_total_maxclients"];
	        this.serverinstance_database_version = source["serverinstance_database_version"];
	        this.serverinstance_filetransfer_port = source["serverinstance_filetransfer_port"];
	        this.serverinstance_guest_serverquery_group = source["serverinstance_guest_serverquery_group"];
	        this.serverinstance_max_download_total_bandwidth = source["serverinstance_max_download_total_bandwidth"];
	        this.serverinstance_max_upload_total_bandwidth = source["serverinstance_max_upload_total_bandwidth"];
	        this.serverinstance_pending_connections_per_ip = source["serverinstance_pending_connections_per_ip"];
	        this.serverinstance_permissions_version = source["serverinstance_permissions_version"];
	        this.serverinstance_serverquery_ban_time = source["serverinstance_serverquery_ban_time"];
	        this.serverinstance_serverquery_flood_commands = source["serverinstance_serverquery_flood_commands"];
	        this.serverinstance_serverquery_flood_time = source["serverinstance_serverquery_flood_time"];
	        this.serverinstance_serverquery_max_connections_per_ip = source["serverinstance_serverquery_max_connections_per_ip"];
	        this.serverinstance_template_channeladmin_group = source["serverinstance_template_channeladmin_group"];
	        this.serverinstance_template_channeldefault_group = source["serverinstance_template_channeldefault_group"];
	        this.serverinstance_template_serveradmin_group = source["serverinstance_template_serveradmin_group"];
	        this.serverinstance_template_serverdefault_group = source["serverinstance_template_serverdefault_group"];
	        this.file_size = source["file_size"];
	        this.l = source["l"];
	        this.last_pos = source["last_pos"];
	        this.msgid = source["msgid"];
	        this.subject = source["subject"];
	        this.permsid = source["permsid"];
	        this.permname = source["permname"];
	        this.permdesc = source["permdesc"];
	        this.token = source["token"];
	        this.token_created = source["token_created"];
	        this.token_customset = source["token_customset"];
	        this.token_description = source["token_description"];
	        this.token_id1 = source["token_id1"];
	        this.token_id2 = source["token_id2"];
	        this.token_type = source["token_type"];
	        this.virtualserver_port = source["virtualserver_port"];
	        this.sgid = source["sgid"];
	        this.n_member_addp = source["n_member_addp"];
	        this.n_member_removep = source["n_member_removep"];
	        this.n_modifyp = source["n_modifyp"];
	        this.namemode = source["namemode"];
	        this.sortid = source["sortid"];
	        this.server_id = source["server_id"];
	        this.connection_bytes_received_control = source["connection_bytes_received_control"];
	        this.connection_bytes_received_speech = source["connection_bytes_received_speech"];
	        this.connection_bytes_sent_control = source["connection_bytes_sent_control"];
	        this.connection_bytes_received_keepalive = source["connection_bytes_received_keepalive"];
	        this.connection_bytes_sent_keepalive = source["connection_bytes_sent_keepalive"];
	        this.connection_bytes_sent_speech = source["connection_bytes_sent_speech"];
	        this.connection_packets_received_control = source["connection_packets_received_control"];
	        this.connection_packets_received_keepalive = source["connection_packets_received_keepalive"];
	        this.connection_packets_received_speech = source["connection_packets_received_speech"];
	        this.connection_packets_sent_control = source["connection_packets_sent_control"];
	        this.connection_packets_sent_keepalive = source["connection_packets_sent_keepalive"];
	        this.connection_packets_sent_speech = source["connection_packets_sent_speech"];
	        this.virtualserver_antiflood_points_needed_command_block = source["virtualserver_antiflood_points_needed_command_block"];
	        this.virtualserver_antiflood_points_needed_ip_block = source["virtualserver_antiflood_points_needed_ip_block"];
	        this.virtualserver_antiflood_points_needed_plugin_block = source["virtualserver_antiflood_points_needed_plugin_block"];
	        this.virtualserver_antiflood_points_tick_reduce = source["virtualserver_antiflood_points_tick_reduce"];
	        this.virtualserver_ask_for_privilegekey = source["virtualserver_ask_for_privilegekey"];
	        this.virtualserver_autostart = source["virtualserver_autostart"];
	        this.virtualserver_capability_extensions = source["virtualserver_capability_extensions"];
	        this.virtualserver_channel_temp_delete_delay_default = source["virtualserver_channel_temp_delete_delay_default"];
	        this.virtualserver_channelsonline = source["virtualserver_channelsonline"];
	        this.virtualserver_client_connections = source["virtualserver_client_connections"];
	        this.virtualserver_clientsonline = source["virtualserver_clientsonline"];
	        this.virtualserver_codec_encryption_mode = source["virtualserver_codec_encryption_mode"];
	        this.virtualserver_complain_autoban_count = source["virtualserver_complain_autoban_count"];
	        this.virtualserver_complain_autoban_time = source["virtualserver_complain_autoban_time"];
	        this.virtualserver_complain_remove_time = source["virtualserver_complain_remove_time"];
	        this.virtualserver_created = source["virtualserver_created"];
	        this.virtualserver_default_channel_admin_group = source["virtualserver_default_channel_admin_group"];
	        this.virtualserver_default_channel_group = source["virtualserver_default_channel_group"];
	        this.virtualserver_default_server_group = source["virtualserver_default_server_group"];
	        this.virtualserver_download_quota = source["virtualserver_download_quota"];
	        this.virtualserver_file_storage_class = source["virtualserver_file_storage_class"];
	        this.virtualserver_filebase = source["virtualserver_filebase"];
	        this.virtualserver_flag_password = source["virtualserver_flag_password"];
	        this.virtualserver_hostbanner_gfx_interval = source["virtualserver_hostbanner_gfx_interval"];
	        this.virtualserver_hostbanner_gfx_url = source["virtualserver_hostbanner_gfx_url"];
	        this.virtualserver_hostbanner_mode = source["virtualserver_hostbanner_mode"];
	        this.virtualserver_hostbanner_url = source["virtualserver_hostbanner_url"];
	        this.virtualserver_hostbutton_gfx_url = source["virtualserver_hostbutton_gfx_url"];
	        this.virtualserver_hostbutton_tooltip = source["virtualserver_hostbutton_tooltip"];
	        this.virtualserver_hostbutton_url = source["virtualserver_hostbutton_url"];
	        this.virtualserver_hostmessage = source["virtualserver_hostmessage"];
	        this.virtualserver_hostmessage_mode = source["virtualserver_hostmessage_mode"];
	        this.virtualserver_icon_id = source["virtualserver_icon_id"];
	        this.virtualserver_id = source["virtualserver_id"];
	        this.virtualserver_ip = source["virtualserver_ip"];
	        this.virtualserver_log_channel = source["virtualserver_log_channel"];
	        this.virtualserver_log_client = source["virtualserver_log_client"];
	        this.virtualserver_log_filetransfer = source["virtualserver_log_filetransfer"];
	        this.virtualserver_log_permissions = source["virtualserver_log_permissions"];
	        this.virtualserver_log_query = source["virtualserver_log_query"];
	        this.virtualserver_log_server = source["virtualserver_log_server"];
	        this.virtualserver_machine_id = source["virtualserver_machine_id"];
	        this.virtualserver_max_download_total_bandwidth = source["virtualserver_max_download_total_bandwidth"];
	        this.virtualserver_max_upload_total_bandwidth = source["virtualserver_max_upload_total_bandwidth"];
	        this.virtualserver_maxclients = source["virtualserver_maxclients"];
	        this.virtualserver_min_android_version = source["virtualserver_min_android_version"];
	        this.virtualserver_min_client_version = source["virtualserver_min_client_version"];
	        this.virtualserver_min_clients_in_channel_before_forced_silence = source["virtualserver_min_clients_in_channel_before_forced_silence"];
	        this.virtualserver_min_ios_version = source["virtualserver_min_ios_version"];
	        this.virtualserver_month_bytes_downloaded = source["virtualserver_month_bytes_downloaded"];
	        this.virtualserver_month_bytes_uploaded = source["virtualserver_month_bytes_uploaded"];
	        this.virtualserver_name = source["virtualserver_name"];
	        this.virtualserver_name_phonetic = source["virtualserver_name_phonetic"];
	        this.virtualserver_needed_identity_security_level = source["virtualserver_needed_identity_security_level"];
	        this.virtualserver_nickname = source["virtualserver_nickname"];
	        this.virtualserver_password = source["virtualserver_password"];
	        this.virtualserver_platform = source["virtualserver_platform"];
	        this.virtualserver_priority_speaker_dimm_modificator = source["virtualserver_priority_speaker_dimm_modificator"];
	        this.virtualserver_query_client_connections = source["virtualserver_query_client_connections"];
	        this.virtualserver_queryclientsonline = source["virtualserver_queryclientsonline"];
	        this.virtualserver_reserved_slots = source["virtualserver_reserved_slots"];
	        this.virtualserver_status = source["virtualserver_status"];
	        this.virtualserver_total_bytes_downloaded = source["virtualserver_total_bytes_downloaded"];
	        this.virtualserver_total_bytes_uploaded = source["virtualserver_total_bytes_uploaded"];
	        this.virtualserver_total_packetloss_control = source["virtualserver_total_packetloss_control"];
	        this.virtualserver_total_packetloss_keepalive = source["virtualserver_total_packetloss_keepalive"];
	        this.virtualserver_total_packetloss_speech = source["virtualserver_total_packetloss_speech"];
	        this.virtualserver_total_packetloss_total = source["virtualserver_total_packetloss_total"];
	        this.virtualserver_total_ping = source["virtualserver_total_ping"];
	        this.virtualserver_unique_identifier = source["virtualserver_unique_identifier"];
	        this.virtualserver_upload_quota = source["virtualserver_upload_quota"];
	        this.virtualserver_uptime = source["virtualserver_uptime"];
	        this.virtualserver_version = source["virtualserver_version"];
	        this.virtualserver_weblist_enabled = source["virtualserver_weblist_enabled"];
	        this.virtualserver_welcomemessage = source["virtualserver_welcomemessage"];
	        this.connection_packetloss_total = source["connection_packetloss_total"];
	        this.connection_ping = source["connection_ping"];
	        this.data = source["data"];
	        this.version = source["version"];
	        this.nickname = source["nickname"];
	        this.desc = source["desc"];
	        this.pw_clear = source["pw_clear"];
	        this.start = source["start"];
	        this.end = source["end"];
	        this.tcid = source["tcid"];
	        this.build = source["build"];
	        this.platform = source["platform"];
	        this.client_channel_id = source["client_channel_id"];
	        this.client_id = source["client_id"];
	        this.client_origin_server_id = source["client_origin_server_id"];
	    }
	}
	export class Result {
	    code: number;
	    message: string;
	    extra_message?: string;
	
	    static createFrom(source: any = {}) {
	        return new Result(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.code = source["code"];
	        this.message = source["message"];
	        this.extra_message = source["extra_message"];
	    }
	}
	export class Response {
	    body?: Body[];
	    status: Result;
	
	    static createFrom(source: any = {}) {
	        return new Response(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.body = this.convertValues(source["body"], Body);
	        this.status = this.convertValues(source["status"], Result);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
		    if (!a) {
		        return a;
		    }
		    if (a.slice && a.map) {
		        return (a as any[]).map(elem => this.convertValues(elem, classs));
		    } else if ("object" === typeof a) {
		        if (asMap) {
		            for (const key of Object.keys(a)) {
		                a[key] = new classs(a[key]);
		            }
		            return a;
		        }
		        return new classs(a);
		    }
		    return a;
		}
	}

}

export namespace utils {
	
	export class Server {
	    name: string;
	    url: string;
	    api: string;
	
	    static createFrom(source: any = {}) {
	        return new Server(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.name = source["name"];
	        this.url = source["url"];
	        this.api = source["api"];
	    }
	}

}

