// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetServerData'](arg1, arg2, arg3, arg4);
}

export function GetServerList(arg1) {
  return window['go']['main']['App']['GetServerList'](arg1);
}
