// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ts3_webquery} from '../models';
import {utils} from '../models';

export function GetServerData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<ts3_webquery.Response>;

export function GetServerList(arg1:string):Promise<Array<utils.Server>>;
